name: Build Kernel SDM425
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libncurses5-dev bison flex python3 libssl-dev

      - name: Compile Kernel
        run: |
          # 1. Find the exact Kernel directory
          KERNEL_ROOT=$(find . -name "Makefile" -not -path "*/scripts/*" -printf '%h\n' | head -n 1)
          cd $KERNEL_ROOT
          
          # 2. Setup Environment
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          
          # 3. Explicitly tell the tool where the configs are
          # This ensures it looks exactly in arch/arm64/configs/
          KCONFIG_CONFIG=arch/arm64/configs/msm8937-perf_defconfig
          
          # 4. Starting the build with the specific path
          make msm8937-perf_defconfig
          make -j$(nproc --all)

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Image
          path: ./**/arch/arm64/boot/Image*

